# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' rcpp_hellow()
#' @description
#' Prints basic
#'
#' @param q if we parameterize the function
#'
#' @details
#' \code{rcpp_hello} does basic calling
#'
#' @return
#' Returns a list object
#'
#' @export
rcpp_hellow <- function(q) {
    .Call('RABIT_rcpp_hellow', PACKAGE = 'RABIT', q)
}

